/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountStatusEnum {
    #[serde(rename = "DISCOVERED")]
    Discovered,
    #[serde(rename = "PROCESSING")]
    Processing,
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "SUSPENDED")]
    Suspended,

}

impl ToString for AccountStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Discovered => String::from("DISCOVERED"),
            Self::Processing => String::from("PROCESSING"),
            Self::Ready => String::from("READY"),
            Self::Error => String::from("ERROR"),
            Self::Suspended => String::from("SUSPENDED"),
        }
    }
}

impl Default for AccountStatusEnum {
    fn default() -> AccountStatusEnum {
        Self::Discovered
    }
}




