/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreditorAccount : Creditor account read serializer.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditorAccount {
    /// Unique entry ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Creditor account name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::TypeEnum>,
    /// Creditor account type identifier
    #[serde(rename = "account")]
    pub account: String,
    /// Creditor account currency
    #[serde(rename = "currency")]
    pub currency: String,
    /// Creditor account address country
    #[serde(rename = "address_country", skip_serializing_if = "Option::is_none")]
    pub address_country: Option<String>,
}

impl CreditorAccount {
    /// Creditor account read serializer.
    pub fn new(name: String, account: String, currency: String) -> CreditorAccount {
        CreditorAccount {
            id: None,
            name,
            r#type: None,
            account,
            currency,
            address_country: None,
        }
    }
}


