/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExecutionRuleEnum : * `following` - following * `preceding` - preceding

/// * `following` - following * `preceding` - preceding
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExecutionRuleEnum {
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "preceding")]
    Preceding,

}

impl ToString for ExecutionRuleEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Following => String::from("following"),
            Self::Preceding => String::from("preceding"),
        }
    }
}

impl Default for ExecutionRuleEnum {
    fn default() -> ExecutionRuleEnum {
        Self::Following
    }
}




