/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JwtRefreshRequest : Refresh access token.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JwtRefreshRequest {
    #[serde(rename = "refresh")]
    pub refresh: String,
}

impl JwtRefreshRequest {
    /// Refresh access token.
    pub fn new(refresh: String) -> JwtRefreshRequest {
        JwtRefreshRequest {
            refresh,
        }
    }
}


