/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JwtObtainPairRequest : Obtain JWT pair.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JwtObtainPairRequest {
    /// Secret id from /user-secrets/
    #[serde(rename = "secret_id")]
    pub secret_id: String,
    /// Secret key from /user-secrets/
    #[serde(rename = "secret_key")]
    pub secret_key: String,
}

impl JwtObtainPairRequest {
    /// Obtain JWT pair.
    pub fn new(secret_id: String, secret_key: String) -> JwtObtainPairRequest {
        JwtObtainPairRequest {
            secret_id,
            secret_key,
        }
    }
}


