/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentReadRequest : PaymentReadSerializer.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentReadRequest {
    /// Institution ID for Payment
    #[serde(rename = "institution_id", skip_serializing_if = "Option::is_none")]
    pub institution_id: Option<String>,
    #[serde(rename = "payment_product", skip_serializing_if = "Option::is_none")]
    pub payment_product: Option<crate::models::PaymentProductEnum>,
    /// Redirect URL to your application after payment is done
    #[serde(rename = "redirect", deserialize_with = "Option::deserialize")]
    pub redirect: Option<String>,
    /// Payment description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Payment Custom Payment ID
    #[serde(rename = "custom_payment_id", skip_serializing_if = "Option::is_none")]
    pub custom_payment_id: Option<String>,
    /// Registered creditor account
    #[serde(rename = "creditor_account", skip_serializing_if = "Option::is_none")]
    pub creditor_account: Option<uuid::Uuid>,
    #[serde(rename = "creditor_object", skip_serializing_if = "Option::is_none")]
    pub creditor_object: Option<Box<crate::models::PaymentReadRequestCreditorObject>>,
    #[serde(rename = "debtor_account")]
    pub debtor_account: Box<crate::models::DebtorAccountWriteRequest>,
    #[serde(rename = "instructed_amount")]
    pub instructed_amount: Box<crate::models::PaymentReadRequestInstructedAmount>,
}

impl PaymentReadRequest {
    /// PaymentReadSerializer.
    pub fn new(redirect: Option<String>, debtor_account: crate::models::DebtorAccountWriteRequest, instructed_amount: crate::models::PaymentReadRequestInstructedAmount) -> PaymentReadRequest {
        PaymentReadRequest {
            institution_id: None,
            payment_product: None,
            redirect,
            description: None,
            custom_payment_id: None,
            creditor_account: None,
            creditor_object: None,
            debtor_account: Box::new(debtor_account),
            instructed_amount: Box::new(instructed_amount),
        }
    }
}


