/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentProductEnum : * `T2P` - target-2-payments * `SCT` - sepa-credit-transfers * `ISCT` - instant-sepa-credit-transfer * `CBCT` - cross-border-credit-transfers * `BACS` - Back Payment Scheme * `CHAPS` - CHAPS Payment Scheme * `FPS` - Faster Payment Scheme * `SWIFT` - Swift Payment Service * `BT` - Balance Transfer * `MT` - Money Transfer

/// * `T2P` - target-2-payments * `SCT` - sepa-credit-transfers * `ISCT` - instant-sepa-credit-transfer * `CBCT` - cross-border-credit-transfers * `BACS` - Back Payment Scheme * `CHAPS` - CHAPS Payment Scheme * `FPS` - Faster Payment Scheme * `SWIFT` - Swift Payment Service * `BT` - Balance Transfer * `MT` - Money Transfer
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentProductEnum {
    #[serde(rename = "T2P")]
    T2P,
    #[serde(rename = "SCT")]
    Sct,
    #[serde(rename = "ISCT")]
    Isct,
    #[serde(rename = "CBCT")]
    Cbct,
    #[serde(rename = "BACS")]
    Bacs,
    #[serde(rename = "CHAPS")]
    Chaps,
    #[serde(rename = "FPS")]
    Fps,
    #[serde(rename = "SWIFT")]
    Swift,
    #[serde(rename = "BT")]
    Bt,
    #[serde(rename = "MT")]
    Mt,

}

impl ToString for PaymentProductEnum {
    fn to_string(&self) -> String {
        match self {
            Self::T2P => String::from("T2P"),
            Self::Sct => String::from("SCT"),
            Self::Isct => String::from("ISCT"),
            Self::Cbct => String::from("CBCT"),
            Self::Bacs => String::from("BACS"),
            Self::Chaps => String::from("CHAPS"),
            Self::Fps => String::from("FPS"),
            Self::Swift => String::from("SWIFT"),
            Self::Bt => String::from("BT"),
            Self::Mt => String::from("MT"),
        }
    }
}

impl Default for PaymentProductEnum {
    fn default() -> PaymentProductEnum {
        Self::T2P
    }
}




