/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentTypeEnum : * `single-payment` - payment * `bulk-payment` - bulk-payments * `periodic-payment` - periodic-payments

/// * `single-payment` - payment * `bulk-payment` - bulk-payments * `periodic-payment` - periodic-payments
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentTypeEnum {
    #[serde(rename = "single-payment")]
    SinglePayment,
    #[serde(rename = "bulk-payment")]
    BulkPayment,
    #[serde(rename = "periodic-payment")]
    PeriodicPayment,

}

impl ToString for PaymentTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::SinglePayment => String::from("single-payment"),
            Self::BulkPayment => String::from("bulk-payment"),
            Self::PeriodicPayment => String::from("periodic-payment"),
        }
    }
}

impl Default for PaymentTypeEnum {
    fn default() -> PaymentTypeEnum {
        Self::SinglePayment
    }
}




