/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaymentWriteRequestDebtorAccount : Debtor account



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentWriteRequestDebtorAccount {
    /// Debtor account currency
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Debtor account type identifier
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    /// Debtor account type identifier
    #[serde(rename = "type_number", skip_serializing_if = "Option::is_none")]
    pub type_number: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::TypeEnum>,
    /// Debtor account name
    #[serde(rename = "name")]
    pub name: String,
    /// Debtor account address country
    #[serde(rename = "address_country", skip_serializing_if = "Option::is_none")]
    pub address_country: Option<String>,
    /// Debtor account post code
    #[serde(rename = "post_code", skip_serializing_if = "Option::is_none")]
    pub post_code: Option<String>,
    /// Debtor account address street
    #[serde(rename = "address_street", skip_serializing_if = "Option::is_none")]
    pub address_street: Option<String>,
}

impl PaymentWriteRequestDebtorAccount {
    /// Debtor account
    pub fn new(name: String) -> PaymentWriteRequestDebtorAccount {
        PaymentWriteRequestDebtorAccount {
            currency: None,
            account: None,
            type_number: None,
            r#type: None,
            name,
            address_country: None,
            post_code: None,
            address_street: None,
        }
    }
}


