/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PremiumAccountQuery : Filter country.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PremiumAccountQuery {
    #[serde(rename = "date_from", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    #[serde(rename = "date_to", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<crate::models::CountryEnum>,
}

impl PremiumAccountQuery {
    /// Filter country.
    pub fn new() -> PremiumAccountQuery {
        PremiumAccountQuery {
            date_from: None,
            date_to: None,
            country: None,
        }
    }
}


