name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@just
      - name: Install openapi-generator-cli
        run: npm install @openapitools/openapi-generator-cli -g
      - uses: actions/checkout@v3
      - run: just build-api
      - run: cargo build --all
      - run: cargo test --all
